### ISSUE TITLE
Setup testing

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/seekr#4]
Setup testing with jest and typescript. Once this is done, we can start adding small tests to the project.

**Comment by imanpalsingh** [comment]
Hey, can I pick this up?

**Comment by blenderskool** [comment]
@imanpalsingh Sure please go ahead!

**Comment by imanpalsingh** [comment]
Great, please assign me

**Comment by imanpalsingh** [comment]
Hey, which node version are you using?

**Comment by blenderskool** [comment]
@imanpalsingh This project uses Node v16.

**Comment by imanpalsingh** [comment]
Please have a look at https://github.com/blenderskool/seekr/pull/5
